import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ReactQueryProvider } from "../lib/react-query";

export const metadata: Metadata = {
  title: {
    template: "%s | Kanban",
    default: "Kanban",
  },
  description: "Generated by create next app",
};

const interFont = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={interFont.className}>
      <body className="bg-navy-950 text-navy-50 antialiased">
        <NuqsAdapter>
          <>
            <ReactQueryProvider>
              <Header />
              {children}
            </ReactQueryProvider>
          </>
        </NuqsAdapter>
      </body>
    </html>
  );
}
